<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php echo $this->view->meta['title']; ?></title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="<?php echo $this->view->meta['description']; ?>">
	<meta name="keywords" content="<?php echo $this->view->meta['keywords']; ?>">

	<!-- Bootstrap 3 CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

	<!-- Font Awesome CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    <!-- Normalize CSS -->
    <link rel="stylesheet" href="<?php echo $this->view->base_url; ?>/skins/default/css/normalize.css">

	<!-- Insert file CSS here ! -->

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<script src="<?php echo $this->view->base_url; ?>/skin/default/js/ie/excanvas.js"></script>
    <![endif]-->
</head>
<body>
	<!-- .content -->
	<div class="container-fluid">
		<?php echo $this->view->content; ?>
	</div>
	<!-- /.content -->
	<!-- .javascript -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
	<!-- Insert file javascript here ! -->
	<!-- /.javascript -->
</body>
</html>