<h1><?php echo _('Bonjour tout le monde !'); ?></h1>
<h2><small><?php echo _('Bienvenue sur le framework Cook !'); ?></small></h2>
<div class="col-lg-6" style="margin:50px 0; padding:0">
<div class="dropdown" style="margin-bottom:25px">
	<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
		<?php echo _('Langues'); ?>
		<span class="caret"></span>
	</button>
	<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
		<li><a href="<?php echo $this->baseUrl; ?>/change/fr"><?php echo _('Français'); ?></a></li>
		<li><a href="<?php echo $this->baseUrl; ?>/change/en"><?php echo _('English'); ?></a></li>
	</ul>
</div>
	<form action="/test/" method="post" accept-charset="utf-8">
	    <div class="input-group">
			<input type="text" class="form-control" placeholder="<?php echo _('Mon prénom'); ?>" name="firstname" id="firstname">
			<span class="input-group-btn">
				<button class="btn btn-default" type="submit"><?php echo _('Allez !'); ?></button>
			</span>
	    </div>
	</form>
</div>