<h1>Hello, world!</h1>
<h2><small>Welcome to the framework Cook !</small></h2>
<div class="col-lg-6" style="margin:50px 0; padding:0">
	<form action="/test/" method="post" accept-charset="utf-8">
	    <div class="input-group">
			<input type="text" class="form-control" placeholder="Mon prénom" name="firstname" id="firstname">
			<span class="input-group-btn">
				<button class="btn btn-default" type="button">Go!</button>
			</span>
	    </div>
	</form>
</div>